### ISSUE TITLE
Modpack Licensing?

### ISSUE THREAD

**Issue by Mad3ngineer** [gamax92/MassSound#8]
gamax92,
I have looked through both your GitHub and your forum post on the OpenComputers forums, searching for information on how you allow your mod to be used in modpacks. I am hoping to add your mod to my modpack, and I was hoping you would give me some more info, and maybe even add this info to your forum post as well.

Thanks
-Mad

**Comment by gamax92** [comment]
Yeah feel free to add it if you'd like, I don't care.

**Comment by Mad3ngineer** [comment]
Thanks gamax, I appreciate it!
