### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by TomyLobo** [gamax92/MassSound#9]
Hi there
Are you still maintaining this addon?

If you port it to 1.10.2 (and it's good :P), I'll contribute the generative sound portion of this mod to it under an open-source license of your choice:

[[1.4.7] [CC 1.481] CCNoise - generate custom sounds](http://www.computercraft.info/forums2/index.php?/topic/12493-147-cc-1481-ccnoise-generate-custom-sounds/)
[CCNoise 0.0.4c quick demo](https://youtu.be/yu2eT2yygW8)

**Comment by gamax92** [comment]
Updated mod to 1.9.4, OC 1.6
Computronics has a beep card, noise card, and sound card that covers something like CCNoise for OpenComputers.

**Comment by TomyLobo** [comment]
Alright, I offered my sound generator there
